# Generated by Django 2.0.2 on 2018-05-07 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall_of_shame', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='score',
        ),
    ]
