# Generated by Django 2.0.2 on 2018-05-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0008_game_finished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='score',
            new_name='points',
        ),
    ]
