# Generated by Django 2.0.2 on 2018-05-09 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0009_auto_20180508_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='home_goals',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
