# Generated by Django 2.0.2 on 2018-05-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0010_auto_20180509_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='home_goals',
            field=models.IntegerField(null=True),
        ),
    ]
