# Generated by Django 2.0.2 on 2018-05-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0011_auto_20180509_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='votable',
            field=models.BooleanField(default=False),
        ),
    ]
