# Generated by Django 2.0.2 on 2018-05-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0013_game_predictions_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
